# -*- coding: utf-8 -*-
"""data_augmentation

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KmUPpuav_MaAEinqmU487JdEOfIB9X2W

# **DATA AUGMENTATION**
"""

import tensorflow as tf

!pip install -q keras

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import keras
from keras.preprocessing.image import ImageDataGenerator, array_to_img, img_to_array,load_img
import os
import cv2

datagen = ImageDataGenerator(
            rotation_range=1,
            width_shift_range=0.05,
            height_shift_range=0.05,
            shear_range=0.1,
            zoom_range=0.08,
            brightness_range=(0.5,1.2),
            fill_mode='constant'
            )

def data_aug(category,multiplier):
  basepath ='/content/drive/My Drive/Colab Notebooks/Pneumonia_classifier/data_covid'
  path = os.path.join(basepath,category)
  for img in os.listdir(path):
      img = load_img(os.path.join(path,img))
      x = img_to_array(img)
      x = x.reshape((1,)+x.shape)
      i = 0
      for batch in datagen.flow(x, batch_size=1,save_to_dir=path,save_format='jpeg'):
          i += 1
          if i >=multiplier:
              break

data_aug('NORMAL',20)

data_aug('PNEUMONIA',20)